addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libspatialindex-dev

language: python

python:
  - 3.6
  - 3.5

before_install:
  - sudo apt-get -y update
  - pip install --upgrade pip
  - pip install --upgrade wheel

install:
  - pip install -r requirements.txt

script:
  - PYTHONPATH=. py.test
